#include "item.hpp"

using namespace RoadRunner::items;

Item* Item::items[512];

Item* Item::shovel_iron;
Item* Item::pickAxe_iron;
Item* Item::hatchet_iron;
Item* Item::flintAndSteel;
Item* Item::apple;
Item* Item::bow;
Item* Item::arrow;
Item* Item::coal;
Item* Item::emerald;
Item* Item::ironIngot;
Item* Item::goldIngot;
Item* Item::sword_iron;
Item* Item::sword_wood;
Item* Item::shovel_wood;
Item* Item::pickAxe_wood;
Item* Item::hatchet_wood;
Item* Item::sword_stone;
Item* Item::shovel_stone;
Item* Item::pickAxe_stone;
Item* Item::hatchet_stone;
Item* Item::sword_emerald;
Item* Item::shovel_emerald;
Item* Item::pickAxe_emerald;
Item* Item::hatchet_emerald;
Item* Item::stick;
Item* Item::bowl;
Item* Item::mushroomStew;
Item* Item::sword_gold;
Item* Item::shovel_gold;
Item* Item::pickAxe_gold;
Item* Item::hatchet_gold;
Item* Item::string;
Item* Item::feather;
Item* Item::sulphur;
Item* Item::hoe_wood;
Item* Item::hoe_stone;
Item* Item::hoe_iron;
Item* Item::hoe_emerald;
Item* Item::hoe_gold;
Item* Item::seeds_wheat;
Item* Item::wheat;
Item* Item::bread;
Item* Item::helmet_cloth;
Item* Item::chestplate_cloth;
Item* Item::leggings_cloth;
Item* Item::boots_cloth;
Item* Item::helmet_chain;
Item* Item::chestplate_chain;
Item* Item::leggings_chain;
Item* Item::boots_chain;
Item* Item::helmet_iron;
Item* Item::chestplate_iron;
Item* Item::leggings_iron;
Item* Item::boots_iron;
Item* Item::helmet_diamond;
Item* Item::chestplate_diamond;
Item* Item::leggings_diamond;
Item* Item::boots_diamond;
Item* Item::helmet_gold;
Item* Item::chestplate_gold;
Item* Item::leggings_gold;
Item* Item::boots_gold;
Item* Item::flint;
Item* Item::porkChop_raw;
Item* Item::porkChop_cooked;
Item* Item::painting;
Item* Item::sign;
Item* Item::door_wood;
Item* Item::bucket;
Item* Item::minecart;
Item* Item::saddle;
Item* Item::door_iron;
Item* Item::redStone;
Item* Item::snowBall;
Item* Item::leather;
Item* Item::brick;
Item* Item::clay;
Item* Item::reeds;
Item* Item::paper;
Item* Item::book;
Item* Item::slimeBall;
Item* Item::egg;
Item* Item::compass;
Item* Item::clock;
Item* Item::yellowDust;
Item* Item::dye_powder;
Item* Item::bone;
Item* Item::sugar;
Item* Item::cake;
Item* Item::bed;
Item* Item::shears;
Item* Item::melon;
Item* Item::seeds_pumpkin;
Item* Item::seeds_melon;
Item* Item::beef_raw;
Item* Item::beef_cooked;
Item* Item::chicken_raw;
Item* Item::chicken_cooked;
Item* Item::mobPlacer;
Item* Item::carrot;
Item* Item::potato;
Item* Item::potatoBaked;
Item* Item::pumpkinPie;
Item* Item::netherbrick;
Item* Item::netherQuartz;
Item* Item::camera;
Item* Item::beetroot;
Item* Item::seeds_beetroot;
Item* Item::beetrootSoup;

Item::Tier WOOD(0, 59, 2.0f, 0);
Item::Tier STONE(1, 131, 4.0f, 1);
Item::Tier IRON(2, 250, 6.0f, 2);
Item::Tier DIAMOND(3, 1561, 8.0f, 3);
Item::Tier GOLD(0, 32, 12.0f, 0);

void Item::initItems(){
	
}
